# -*- coding: utf-8 -*-
"""Classes & Objects.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1baO8EmMagnNllQ-Wp9orDRdN9ljOvYG4
"""

emp_details = { "employee1" : {"name" : "Karthik", "age" : 25, "location" : "Vizag"}, 
               "employee2" : {"name" : "Karthik", "age" : 25, "location" : "Vizag"},
               "employee3" : {"name" : "Karthik", "age" : 25, "location" : "Vizag"},
               "employee1" : {"name" : "Karthik", "age" : 25, "location" : "Vizag"}
               }


employee1 = ("Karthik", 25, "Vizag")
employee2 = ["Charan", 26, "Hyderabd"]
employee3 = ["Karan", 28, "Nellore"]
employee4 = ["Arjun", 24, "Vijayawada"]
print(type(employee1))
print(type(employee2))
print(employee2)
print(type(employee3))


# create basic data structure with properties(details) - CLASS
# using this basic structure we can create objects

"""Classes & Objects

Classes - blueprint of user defined data structure
Objects - Instance of the class

Init - a constructor which will be instantiated with the properties/attribute/variables defined when we create an object

self = its a parameter which refers to the current instance of class
"""

class EmployeeDetails:
  def __init__(self,name,age,location):
    self.name = name
    self.age = age
    self.location = location

  # Instance Method
  def display(self):
    print(self.name, " is of ", self.age, " years old living in ", self.location)

obj1 = EmployeeDetails("Charan", 26, "Hyderabad")
obj2 = EmployeeDetails("Arjun", 24, "Vijayawada")
print(obj1.name)
print(obj2.location)
obj1.display()
obj2.display()