# -*- coding: utf-8 -*-
"""Lists & Tuples Methods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1htqz9W0PanfFxaA2MQc7-YLGsCXSKi84
"""

f1 = [35, "Python Programming", 54, 35, "computer", "memory", 31.9,22.5, [98,"surprising",67], (21, "allocation", 11, 33.4)]

# f1.remove(35)
# print(f1)
# f1.pop()
# print(f1)
# f1.remove("computer")
# print(f1)
# f1.pop(4)
# print(f1)
# f1.clear()
# print(f1)
# f1.append("Sparkle")
# print(f1)
# del f1
# print(f1)
# f1.append("Sparkle")
# print(f1)
# f1.extend("Sparkle")
# print(f1)
# f1.insert(12,"orange")
# print(f1)
# print(f1.index("memory"))
# f2 = [2, 1, 5, 4]
# f1.append(f2)
# f1.extend(f2)
# print(f1)
# f2.sort(reverse = True)
# f2.sort(reverse = False)
# print(f2)
# print(f1.count(35))
# print(f1.count(54))
# print(f1[::-1])
# print(f1)
# f1.reverse()
# print(f1)
# z = f1.copy()
# print(z)

t = (35, 'Python Programming', 54, 35, 'computer', 'memory')
# print(t.count(35))
# print(t.index(35))
# temp_t = list(t)
# print(temp_t)
# temp_t.remove(35)
# print(temp_t)
# print(tuple(temp_t))

print(tuple(f1) + t)
3 + "orange" + [ ] + ()

"""remove vs pop
clear vs del
append vs extend vs insert
reverse vs slicing reverse
"""