# -*- coding: utf-8 -*-
"""Slicing Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNHLbpjKkBFbZ2gJgGfpvIZVYQi3vXvz
"""

s = "Monty Python's Flying Circus"
print("1.", s)
print("2.", len(s))
print("3.", s[:])
print("4.", s[::])
print("5.", s[0:len(s):1])
print("6.", s[1:])
print("7.", s[-1:])
print("8.", s[1:-1])
print("9.", s[1:-1])
print("10.", s[-1])
print("11.", s[::-1])
print("12.", s[::-2])
print("13.", s[::1])
print("14.", s[::2])
print("15.", s[::3])
print("16.", s[:-3])
print("17.", s[-3::-1])
print("18.", s[-3::1])
print("19.", s[13::-1])
print("20.", s[13::1])
print("21.", s[1:1:1])
print("22.", s[1::1])
print("23.", s[-1::-1])
print("24.", s[3:-27])
print("25.", s[4:-17])
print("26.", s[-21:-11])
print("27.", s[-21:11])
print("28.", s[21:11])
print("29.", s[21:-11])
print("30.", s[13::-1])
print("31.", s[13::1])
print("32.", s[:15:-1])
print("33.", s[:15:1])
print("34.", s[21:-11:-1])
print("35.", s[13:-13:-1])
print("36.", s[5:-8:1])
print("37.", s[5:-8:-1])
print("38.", s[5:8:1])
print("39.", s[5:8:-1])
print("40.", s[-5:-8:1])
print("41.", s[-5:-8:-1])
print("42.", s[-5:8:1])
print("43.", s[-5:8:-1])
print("44.", s[8:-5:2])
print("45.", s[8:-5:-2])
print("46.", s[-8:-5:2])
print("47.", s[-8:-5:-2])
print("48.", s[-8:5:2])
print("49.", s[-8:5:-2])
print("50.", s[8:-5:2])
print("51.", s[8:-5:-2])
print("52.", s[30:])
print("53.", s[30])

# Print the below words using slicing & concatenation
# 1. Moon
# 2. Crying
# 3. MontyPython'sFlyingCircus