# -*- coding: utf-8 -*-
"""Variables & Numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdJAOgVxNuCsKTTa1oEqJjoQmoPMHVBD
"""

x = 10
y = 10
x = x+1
print(x)
print(y)
print(id(x))
print(id(y))
print(id(x)==id(y))
y = 20
z = 14
print(y)
print(id(y))
print(z)
print(id(z))

b = 15.6
_m1 = "Python"
print(_m1)

del _m1


num1 = 10
num2,num3,num4 = 20,30,40
num5 = num6 = num7 = 50
print(num1) # Printing the value of number 1
print(num2)
print(num3)
print(num4)
print(num5)
print(num6)
print(num7)
print(num8)

# STRINGS = 'Python', "Python", '''Python'''
s1 = "Python"
print(s1)
s2 = "He asked me \"Where are you going?\""

print(s2)

s3 = 'I\'m at the location'
print(s3)