# -*- coding: utf-8 -*-
"""Encapsulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rslZ_tsFkTxLJocWf2GdkwH2aguj4PGK
"""

class EmployeeDetails:
  def __init__(self,name,age,location):
    self._name = name # Protected
    self.__age = age # Private
    self.location = location # Public

  def age_details(self):
    print(self.name, " is of ", self.age, " years old")

  def address_details(self):
    print(self.__name, " is living in ", self.location)

class Company(EmployeeDetails):
  pass

emp1 = EmployeeDetails("Karthik",25,"Hyderabad")
emp1._name
emp1.name = "Charan"
emp1.name
# emp1.address_details()

def outer():
  s = 12
  def inner():
    t = 30
    print(s)
    print(t)
  print(s)
  print(t)

outer()

"""Access Modifiers - 3 types

1. Public Data - Global
2. Protected - Enclosed
3. Private - Local
"""

